run:
  tests: false

linters-settings:
  govet:
    check-shadowing: false
  misspell:
    locale: US

linters:
  enable-all: true
  disable:
    - maligned
    - lll
    - gocritic
    - gochecknoinits
    - gochecknoglobals
    - deadcode
    - unused
    - errcheck
    - unparam
    - dupl
    - gocyclo
    - wsl
    - gomnd
    - stylecheck
    - goconst
    - unparam
    - gochecknoglobals
    - gochecknoinits
    - funlen
    - gocritic
    - gocognit
    - gocyclo
    - gosec
    - dogsled

issues:
  exclude-use-default: false
  exclude-rules:
    - linters:
        - staticcheck
      text: "SA1012:"
